name: GitHub Copilot Agent

on:
  workflow_dispatch:
  schedule:
    # Run on a schedule to keep the agent active
    - cron: '0 0 * * *'

env:
  # Global environment variables for Copilot Agent access
  COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS: "blues.io,blues.com"
  COPILOT_AGENT_DNS_ALLOW_LIST_ADDITIONS: "blues.io,blues.com,dev.blues.io"
  COPILOT_AGENT_FIREWALL_DNS_ALLOW_LIST_ADDITIONS: "blues.io,blues.com,dev.blues.io"

jobs:
  configure-copilot-agent:
    runs-on: ubuntu-latest

    env:
      # Allow access to blues.io and blues.com domains for Copilot Agent
      COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS: "blues.io,blues.com"
      # Allow DNS resolution for blues.io domains
      COPILOT_AGENT_DNS_ALLOW_LIST_ADDITIONS: "blues.io,blues.com,dev.blues.io"
      # Configure DNS resolution permissions
      COPILOT_AGENT_FIREWALL_DNS_ALLOW_LIST_ADDITIONS: "blues.io,blues.com,dev.blues.io"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Copilot Agent Access
        run: |
          echo "Configuring GitHub Copilot Agent with domain access:"
          echo "Allowed domains: $COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS"
          echo "DNS allowed domains: $COPILOT_AGENT_DNS_ALLOW_LIST_ADDITIONS"
          echo "Firewall DNS allowed domains: $COPILOT_AGENT_FIREWALL_DNS_ALLOW_LIST_ADDITIONS"
          echo "This allows the Copilot Agent to access:"
          echo "- https://dev.blues.io for API documentation and resources"
          echo "- https://discuss.blues.com for community discussions and support"
