name: Copilot Setup Steps

# This file configures the development environment for GitHub Copilot

on:
  workflow_dispatch

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up
  # by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    env:
      COPILOT_AGENT_FIREWALL_ENABLED: false
      # COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS: blues.io,blues.com

    # Set the permissions to the lowest permissions possible needed for your
    # steps. Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for
      # example to install dependencies, you'll need the `contents: read`
      # permission. If you don't clone the repository in your setup steps,
      # Copilot will do this for you automatically after the steps complete.
      contents: read

    steps:
      - run: echo 'COPILOT_AGENT_FIREWALL_ENABLED' || echo ${COPILOT_AGENT_FIREWALL_ENABLED}
      - run: echo 'COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS' || echo ${COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS}
      - run: echo "Setup complete"
