name: Publish API Documentation (Static Site)

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master # Or master, depending on your CI workflow's branch
  push:
    branches:
      - master
    paths:
      - '**.json'
      - 'scripts/generate_docs.py'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Condition to ensure the CI workflow was successful
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push') || (github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Pipenv
        run: python -m pip install --upgrade pip pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Generate documentation
        run: |
          pipenv run python scripts/generate_docs.py

      - name: Build site
        run: |
          pipenv run mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
