name: Publish API Documentation

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master # Or master, depending on your CI workflow's branch
  push:
    branches:
      - master
    paths:
      - '**.json'
      - 'scripts/generate_docs.py'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Condition to ensure the CI workflow was successful
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push') || (github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate documentation
        run: |
          python scripts/generate_docs.py

      - name: Rename documentation to index.md for Jekyll
        run: |
          mv NOTECARD_API.md index.md

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: jekyll
          enablement: true

      - name: Create Jekyll config
        run: |
          cat > _config.yml << EOF
          theme: jekyll-theme-cayman
          title: Notecard API Reference
          description: API documentation for the Notecard
          show_downloads: false
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
